### ISSUE TITLE
Fails to compile on Linux 6.8.1

### ISSUE THREAD

**Issue by tyisafk** [NulliferBones/lg4k-linux#3]
Compiles like it should on linux-lts (6.6) but still face the atomic bug.  Attempting to compile on kernel 6.8.1 results in this make error.  Was on Linux-Zen for this but results are the same on normal 6.8.1 as well.  They seem to be related to v4l2.

Linux headers are installed.

```
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /home/ty/lg4k-linux/driver/utils/v4l2/v4l2_model_ioctl.o] Error 1
make[2]: *** [/usr/lib/modules/6.8.1-zen1-1-zen/build/Makefile:1919: /home/ty/lg4k-linux/driver] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.8.1-zen1-1-zen/build'
make: *** [Makefile:66: build] Error 2
make: Leaving directory '/home/ty/lg4k-linux/driver'
cp: cannot stat 'driver/gc573.ko': No such file or directory
```

**Comment by the-bmt** [comment]
Same error for me on 6.8.1 as well, I have played around a bit with it and got it to compile and load, but it is still not working sadly

**Comment by PeeJayBonobo** [comment]
I also get the same error even with linux-zen 6.9, but the error is within v4l2_model_ioctl.c:

```
/home/peejay_bonobo/lg4k-linux/driver/utils/v4l2/v4l2_model_ioctl.c: In function ‘v4l2_model_ioctl_enum_fmt_vid_cap’:
/home/peejay_bonobo/lg4k-linux/driver/utils/v4l2/v4l2_model_ioctl.c:292:9: error: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Wimplicit-function-declaration]
  292 |         strlcpy(f->description, pixfmt->name, sizeof(f->description));
      |         ^~~~~~~
      |         strncpy
```

And then, after a bunch of warning messages that don't affect compilation at all:
```
make[3]: *** [scripts/Makefile.build:244: /home/peejay_bonobo/lg4k-linux/driver/utils/v4l2/v4l2_model_ioctl.o] Error 1
make[2]: *** [/usr/lib/modules/6.9.1-zen1-1-zen/build/Makefile:1917: /home/peejay_bonobo/lg4k-linux/driver] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.9.1-zen1-1-zen/build'
make: *** [Makefile:66: build] Error 2
make: Leaving directory '/home/peejay_bonobo/lg4k-linux/driver'
cp: cannot stat 'driver/gc573.ko': No such file or directory
```

The solution with kernel 6.8 was to go with the compiler's suggestion of replacing "strlcpy" with "strncpy", but then there's the atomic bug on shutdown.
